### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MrUnknown789556** [Krasjet/pdf.tocgen#21]
I just installed pdf.tocgen without any errors.

When running I got this error messages:

C:\Users\fn31>pdfxmeta -p page -a 1 ABasicStudy.pdf "Section" >> recipe.toml

Traceback (most recent call last):
  File "C:\Users\fn31\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fn31\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\fn31\AppData\Local\Programs\Python\Python310\Scripts\pdfxmeta.exe\__main__.py", line 7, in <module>
  File "C:\Users\fn31\AppData\Local\Programs\Python\Python310\lib\site-packages\pdfxmeta\app.py", line 92, in main
    page = int(a)
ValueError: invalid literal for int() with base 10: 'page'

[ABasicStudy.pdf](https://github.com/Krasjet/pdf.tocgen/files/12130129/ABasicStudy.pdf)

**Comment by Krasjet** [comment]
`page` needs to be replaced by the page number of the string. See also https://github.com/Krasjet/pdf.tocgen/issues/16
