### ISSUE TITLE
pdftocio throws error when saving

### ISSUE THREAD

**Issue by amzon-ex** [Krasjet/pdf.tocgen#27]
Hi, I'm trying to use `pdftocio` to generate a ToC for a pdf. I have already generated the toc file using `pdfxmeta` and 'pdftocgen`. The error is as following:
```
Traceback (most recent call last):
  File "/home/amzon-ex/.local/bin/pdftocio", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/amzon-ex/.local/lib/python3.11/site-packages/pdftocio/app.py", line 163, in main
    doc.save(out)
  File "/home/amzon-ex/.local/lib/python3.11/site-packages/fitz/fitz.py", line 4710, in save
    return _fitz.Document_save(self, filename, garbage, clean, deflate, deflate_images, deflate_fonts, incremental, ascii, expand, linear, no_new_id, appearance, pretty, encryption, permissions, owner_pw, user_pw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot find object in xref (2818 0 R)
```

Can you help?

**Comment by Krasjet** [comment]
seems to be a corrupted pdf file. might be related https://github.com/pymupdf/PyMuPDF/issues/352
