### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by ghost** [Krasjet/pdf.tocgen#37]
I have a `toc` file for a textbook but running `pdftocio linear_algebra_5th_edition.pdf < toc` returns the error in the title. Here's the result with a  `-g` flag:

```
df@tower:~/pdftocgen$ pdftocio -g linear_algebra_5th_edition.pdf < toc_new
Traceback (most recent call last):
  File "/home/df/.local/bin/pdftocio", line 8, in <module>
    sys.exit(main())
  File "/home/df/.local/lib/python3.10/site-packages/pdftocio/app.py", line 166, in main
    raise e
  File "/home/df/.local/lib/python3.10/site-packages/pdftocio/app.py", line 156, in main
    toc = parse_toc(toc_file)
  File "/home/df/.local/lib/python3.10/site-packages/pdftocio/tocparser.py", line 38, in parse_toc
    return list(map(parse_entry, reader))
  File "/home/df/.local/lib/python3.10/site-packages/pdftocio/tocparser.py", line 22, in parse_entry
    int(entry[indent + 1]),  # pagenum
ValueError: invalid literal for int() with base 10: ''
```

and here's the `toc` file.
[toc.txt](https://github.com/user-attachments/files/17071214/toc.txt)

Thanks in advance!

**Comment by Krasjet** [comment]
There is no page number for the line
```
    "6.7* THE SINGULAR VALUE DECOMPOSITION AND THE PSEUDOINVERSE" 
```

I probably need to add a more friendly error message.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
